pipeline:
  dataset_dir: "Dataset"
  shards_subfolder: "Train/shards"
  checkpoints_subfolder: "Train/checkpoints"
  state_file: "train_pipeline_state.json"
  force_recompute: false
  log_level: "INFO"
  log_file: "Dataset/train_pipeline.log"
  step: null               # valori: "clean", "shard", "train_basic", "train_time_aware", "evaluate"
  no_amp: true

clean:
  enabled: true
  input_train: "Dataset/Train/train.pt"
  input_val: "Dataset/Train/val.pt"
  input_test: "Dataset/Train/test.pt"
  output_train: "Dataset/Train/train_clean.pt"
  output_val: "Dataset/Train/val_clean.pt"
  output_test: "Dataset/Test/test_clean.pt"
  workers: 0

shard:
  train_clean: "Dataset/Train/train_clean.pt"
  val_clean: "Dataset/Train/val_clean.pt"
  shard_size: 5900

train_basic:
  enabled: true
  shards_dir: "Dataset/Train/shards"
  checkpoint: "Dataset/Train/checkpoints/basic"
  epochs: 50
  batch_size: 128
  num_workers: 1
  lr: 1.0e-3
  seed: 42
  patience: 5
  embedding_dims: 64
  gat_hidden_dim_event: 32
  gat_hidden_dim_embed: 128
  gat_hidden_dim_concat: 128
  num_heads: 4
  num_layers: 1
  dropout: 0.2
  use_batch_norm: true
  activation: "elu"
  weight_decay: 1.0e-4

train_time_aware:
  enabled: true
  shards_dir: "Dataset/Train/shards"
  checkpoint: "Dataset/Train/checkpoints/time_aware"   # <-- corretto
  epochs: 50
  batch_size: 128
  num_workers: 1
  lr: 1.0e-3
  seed: 42
  patience: 5
  embedding_dims: 64
  gat_hidden_dim_event: 32
  gat_hidden_dim_embed: 128
  gat_hidden_dim_concat: 128
  num_heads: 4
  num_layers: 1
  dropout: 0.2
  use_batch_norm: true
  activation: "elu"
  lambda_decay: 0.01
  weight_decay: 1.0e-4

evaluate:
  enabled: true
  test_data: "Dataset/Test/test_clean.pt"
  plots_dir: "Dataset/Test/plots"
  out_dir: "Dataset/Test/metrics"
  max_n: 10
  batch_size: 128
  num_workers: 2
  model_basic_checkpoint: "Dataset/Train/checkpoints/basic_best.pt"        # <-- corretto
  model_time_aware_checkpoint: "Dataset/Train/checkpoints/time_aware_best.pt"  # <-- corretto