pipeline:
  dataset_dir: "Dataset"
  shards_subfolder: "Train/shards"
  checkpoints_subfolder: "Train/checkpoints"
  state_file: "train_pipeline_state.json"
  force_recompute: false
  log_level: "INFO"
  log_file: "Dataset/train_pipeline.log"
  step: "evaluate"
  no_amp: false

train_basic:
  enabled: true
  train_dir: "Dataset/Train/train_clean"
  val_dir: "Dataset/Train/val_clean"
  checkpoint: "Dataset/Model/checkpoints/basic"
  epochs: 50
  batch_size: 128
  num_workers: 2
  prefetch_factor: 4
  lr: 1.0e-3
  seed: 42
  patience: 5
  embedding_dims: 64
  gat_hidden_dim_event: 32
  gat_hidden_dim_embed: 128
  gat_hidden_dim_concat: 128
  num_heads: 4
  num_layers: 3
  dropout: 0.2
  use_batch_norm: true
  activation: "elu"
  weight_decay: 1.0e-4
  persistent_workers: true
  compile: false
  norm_kind: "layer_norm"

train_time_aware:
  enabled: true
  train_dir: "Dataset/Train/train_clean"
  val_dir: "Dataset/Train/val_clean"
  checkpoint: "Dataset/Train/checkpoints/time_aware"
  epochs: 50
  batch_size: 128
  num_workers: 2
  prefetch_factor: 4
  lr: 2.45e-4
  seed: 42
  patience: 5
  embedding_dims: 64
  gat_hidden_dim_event: 32
  gat_hidden_dim_embed: 128
  gat_hidden_dim_concat: 128
  num_heads: 4
  num_layers: 3
  dropout: 0.2
  use_batch_norm: true
  activation: "elu"
  lambda_decay: 2.0
  weight_decay: 0.05e-4
  persistent_workers: true
  compile: false
  norm_kind: "layer_norm"

evaluate:
  enabled: true
  test_dir: "Dataset/Train/test_clean"
  model_basic_checkpoint: "Models/basic_best.pt"
  model_time_aware_checkpoint: "Models/time_aware_best.pt"
  plots_dir: "Result/TestSet/plots"
  out_dir: "Result/TestSet/metrics"
  max_n: 5
  batch_size: 128
  num_workers: 2
  prefetch_factor: 4
  seed: 42